"""
FakeClue Dataset — Caption Quality & Template Vagueness Analysis
목적: GT 캡션이 얼마나 두루뭉술하고 반복적인 템플릿에 의존하는지 정량화.
     사전 단어장 외에도 active하게 반복 phrase를 발굴해 편입·분석.
"""

import json
import re
import textwrap
from collections import Counter, defaultdict
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
from matplotlib import font_manager
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np
from wordcloud import WordCloud

# ── 한글 폰트 ──────────────────────────────────────────────────────
FONT_PATH = "/System/Library/Fonts/AppleSDGothicNeo.ttc"
font_manager.fontManager.addfont(FONT_PATH)
plt.rcParams["font.family"] = "Apple SD Gothic Neo"
plt.rcParams["axes.unicode_minus"] = False

# ── 경로 ──────────────────────────────────────────────────────────
BASE_DIR  = Path(__file__).resolve().parent
JSON_PATH = BASE_DIR / "FakeClue" / "data_json" / "test.json"
OUT_DIR   = BASE_DIR / "FakeClue_visualized" / "caption_analysis"
OUT_DIR.mkdir(parents=True, exist_ok=True)

CATE_ORDER = ["deepfake", "human", "animal", "object", "scene", "satellite", "doc"]

# ── 사전 정의 Vague Phrase 단어장 ─────────────────────────────────
SEED_VAGUE = [
    "underlying characteristic inconsistencies",
    "artificially created",
    "does not show obvious artifacts",
    "synthetic nature",
    "minor anomalies",
    "overall structure and coherence",
    "convincing illusion",
    "seemingly authentic appearance",
    "ai-generated",
    "generated by ai",
    "further indicating",
    "collectively indicate",
    "further confirms",
    "indicates it is",
    "suggesting it is",
    "appear unnatural",
    "appears unnatural",
    "lacks natural",
    "lack natural",
    "overall consistency",
    "global consistency",
    "upon closer inspection",
]

# ── 1. 데이터 로드 ─────────────────────────────────────────────────
print("📂 데이터 로드 중...")
with open(JSON_PATH, encoding="utf-8") as f:
    raw = json.load(f)

records = []
for item in raw:
    for conv in item["conversations"]:
        if conv["from"] == "gpt":
            records.append({
                "cate":  item.get("cate", "unknown"),
                "label": item.get("label", -1),
                "text":  conv["value"].strip(),
                "lower": conv["value"].lower().strip(),
            })

N = len(records)
print(f"  총 {N:,}개 캡션 로드 완료\n")


# ── 2. N-gram Active 발굴 ─────────────────────────────────────────
def extract_ngrams(texts, n):
    all_ngrams = []
    for t in texts:
        words = re.findall(r"\b[a-z]+\b", t)
        all_ngrams += [" ".join(words[i:i+n]) for i in range(len(words) - n + 1)]
    return Counter(all_ngrams)

print("🔍 N-gram 분석 중 (4·6·8-gram)...")
all_lowers = [r["lower"] for r in records]
cnt4  = extract_ngrams(all_lowers, 4)
cnt6  = extract_ngrams(all_lowers, 6)
cnt8  = extract_ngrams(all_lowers, 8)

# 상위 N-gram 추출 (등장 빈도 > 전체의 5% = 250회 이상)
FREQ_THRESH = int(N * 0.05)
top4  = [(p, c) for p, c in cnt4.most_common(30) if c >= FREQ_THRESH]
top6  = [(p, c) for p, c in cnt6.most_common(20) if c >= FREQ_THRESH]
top8  = [(p, c) for p, c in cnt8.most_common(15) if c >= FREQ_THRESH]

# Active 발굴 후 VAGUE_PHRASES 확장
discovered_phrases = [p for p, _ in top6] + [p for p, _ in top8]
ALL_VAGUE = list(set(SEED_VAGUE + discovered_phrases))
print(f"  사전 정의: {len(SEED_VAGUE)}개 → Active 발굴 후 총 {len(ALL_VAGUE)}개 phrase\n")


# ── 3. Vague Coverage 계산 ────────────────────────────────────────
def vague_flags(record):
    t = record["lower"]
    hits = [p for p in ALL_VAGUE if p in t]
    return hits

for r in records:
    r["vague_hits"] = vague_flags(r)
    r["n_vague"]    = len(r["vague_hits"])
    r["is_vague"]   = r["n_vague"] > 0

n_vague = sum(r["is_vague"] for r in records)
print(f"📊 최소 1개 이상 vague phrase 포함 캡션: {n_vague:,} / {N:,} ({n_vague/N:.1%})")


# ── 4. 카테고리별 통계 집계 ───────────────────────────────────────
cate_stats = {}
for cate in CATE_ORDER:
    sub = [r for r in records if r["cate"] == cate]
    if not sub:
        continue
    fake_sub = [r for r in sub if r["label"] == 0]
    real_sub = [r for r in sub if r["label"] == 1]

    # TTR: Type-Token Ratio (어휘 다양성)
    all_words = re.findall(r"\b[a-z]+\b", " ".join(r["lower"] for r in sub))
    ttr = len(set(all_words)) / len(all_words) if all_words else 0

    # 평균 캡션 길이
    avg_len = np.mean([len(r["text"]) for r in sub])

    # Vague 비율
    v_ratio = np.mean([r["is_vague"] for r in sub])

    # 중복 캡션 비율 (완전 동일)
    texts = [r["lower"] for r in sub]
    dup_ratio = 1 - len(set(texts)) / len(texts)

    # Fake vs Real vague 비율 차이
    fake_v = np.mean([r["is_vague"] for r in fake_sub]) if fake_sub else 0
    real_v = np.mean([r["is_vague"] for r in real_sub]) if real_sub else 0

    cate_stats[cate] = {
        "n": len(sub), "n_fake": len(fake_sub), "n_real": len(real_sub),
        "ttr": ttr, "avg_len": avg_len,
        "vague_ratio": v_ratio,
        "dup_ratio": dup_ratio,
        "fake_vague": fake_v, "real_vague": real_v,
    }


# ── 5. 개별 phrase 빈도 계산 ─────────────────────────────────────
phrase_freq = {}
for p in ALL_VAGUE:
    cnt = sum(1 for r in records if p in r["lower"])
    phrase_freq[p] = cnt
phrase_freq = {k: v for k, v in sorted(phrase_freq.items(), key=lambda x: -x[1]) if v > 0}

# ── 6. 첫 문장 패턴 분석 ─────────────────────────────────────────
first_sentences = []
for r in records:
    sents = re.split(r'(?<=[.!?])\s+', r["text"])
    if sents:
        first_sentences.append(sents[0].lower().strip())

fs_counter = Counter(first_sentences)
top_first_sent = fs_counter.most_common(10)

# 첫 문장 도입부 패턴 (앞 5단어)
first_5w = []
for s in first_sentences:
    words = re.findall(r"\b[a-z]+\b", s)
    if len(words) >= 5:
        first_5w.append(" ".join(words[:5]))
top_first_5w = Counter(first_5w).most_common(15)


# ── 7. 리포트 출력 ────────────────────────────────────────────────
print("\n" + "="*65)
print("FakeClue Caption Quality Analysis — 리포트")
print("="*65)

print(f"\n[1] 전체 캡션 수: {N:,}")
print(f"    Vague phrase 포함: {n_vague:,} ({n_vague/N:.1%})")

print("\n[2] 카테고리별 핵심 지표")
print(f"{'카테고리':<12} {'총':>5} {'Vague%':>8} {'중복%':>7} {'TTR':>6} {'평균길이':>8}")
print("-"*48)
for c in CATE_ORDER:
    if c not in cate_stats:
        continue
    s = cate_stats[c]
    print(f"{c:<12} {s['n']:>5} {s['vague_ratio']:>7.1%} {s['dup_ratio']:>6.1%} "
          f"{s['ttr']:>6.3f} {s['avg_len']:>8.0f}")

print("\n[3] 상위 Vague Phrase 빈도 (상위 20개)")
for i, (p, v) in enumerate(list(phrase_freq.items())[:20], 1):
    origin = "seed" if p in SEED_VAGUE else "발굴"
    print(f"  {i:>2}. [{v:>4}회 / {v/N:.1%}] ({origin}) '{p}'")

print("\n[4] 가장 많이 반복된 첫 문장 (상위 10)")
for sent, cnt in top_first_sent:
    print(f"  [{cnt:>4}회] \"{sent[:80]}\"")

print("\n[5] 첫 5단어 도입부 패턴 (상위 15)")
for pat, cnt in top_first_5w:
    print(f"  [{cnt:>4}회] \"{pat}\"")

print("\n[6] 8-gram 반복 템플릿 (상위 15 / 등장률 5% 이상)")
for p, c in top8[:15]:
    print(f"  [{c:>4}회 / {c/N:.1%}] \"{p}\"")


# ── 8. 시각화 ─────────────────────────────────────────────────────
BG   = "#1a1a2e"
CARD = "#16213e"
RED  = "#E53935"
GRN  = "#43A047"
BLUE = "#1565C0"
GOLD = "#F9A825"
TXT  = "white"

def dark_ax(ax, title=""):
    ax.set_facecolor(CARD)
    for sp in ax.spines.values():
        sp.set_edgecolor("#444")
    ax.tick_params(colors=TXT)
    ax.xaxis.label.set_color(TXT)
    ax.yaxis.label.set_color(TXT)
    if title:
        ax.set_title(title, color=TXT, fontsize=12, fontweight="bold", pad=8)

# ── [Figure 1] Overview Dashboard ────────────────────────────────
fig1 = plt.figure(figsize=(24, 18), facecolor=BG)
fig1.suptitle("FakeClue Dataset — Caption Quality & Vagueness Analysis",
              color=TXT, fontsize=20, fontweight="bold", y=0.98)
gs = gridspec.GridSpec(3, 3, figure=fig1, hspace=0.45, wspace=0.35,
                       top=0.94, bottom=0.05, left=0.06, right=0.97)

# (0,0) Vague 포함 비율 파이
ax = fig1.add_subplot(gs[0, 0])
ax.set_facecolor(CARD)
ax.pie([n_vague, N - n_vague],
       labels=["Vague\n포함", "Vague\n없음"],
       colors=[RED, GRN],
       autopct="%1.1f%%", startangle=140,
       textprops={"color": TXT, "fontsize": 12, "fontweight": "bold"},
       wedgeprops={"edgecolor": BG, "linewidth": 2})
ax.set_title("전체 Vague Phrase 포함 비율", color=TXT, fontsize=12, fontweight="bold")

# (0,1) 카테고리별 Vague 비율 막대
ax = fig1.add_subplot(gs[0, 1])
dark_ax(ax, "카테고리별 Vague 비율 (Fake vs Real)")
cates_v = [c for c in CATE_ORDER if c in cate_stats]
x = np.arange(len(cates_v))
w = 0.35
fake_v_vals = [cate_stats[c]["fake_vague"] * 100 for c in cates_v]
real_v_vals = [cate_stats[c]["real_vague"] * 100 for c in cates_v]
ax.bar(x - w/2, fake_v_vals, width=w, color=RED, label="FAKE", edgecolor=BG)
ax.bar(x + w/2, real_v_vals, width=w, color=GRN, label="REAL", edgecolor=BG)
ax.set_xticks(x)
ax.set_xticklabels(cates_v, rotation=30, ha="right", fontsize=10, color=TXT)
ax.set_ylabel("Vague 포함 비율 (%)", color=TXT, fontsize=10)
ax.set_ylim(0, 105)
ax.legend(facecolor=BG, labelcolor=TXT, fontsize=10)
for i, (f, r) in enumerate(zip(fake_v_vals, real_v_vals)):
    ax.text(i - w/2, f + 1, f"{f:.0f}%", ha="center", fontsize=7.5, color=TXT)
    ax.text(i + w/2, r + 1, f"{r:.0f}%", ha="center", fontsize=7.5, color=TXT)

# (0,2) 카테고리별 TTR (어휘 다양성)
ax = fig1.add_subplot(gs[0, 2])
dark_ax(ax, "카테고리별 어휘 다양성 (TTR)")
ttr_vals = [cate_stats[c]["ttr"] for c in cates_v]
colors_ttr = plt.cm.RdYlGn(np.array(ttr_vals) / max(ttr_vals))
bars = ax.bar(cates_v, ttr_vals, color=colors_ttr, edgecolor=BG)
ax.set_xticklabels(cates_v, rotation=30, ha="right", fontsize=10, color=TXT)
ax.set_ylabel("Type-Token Ratio", color=TXT, fontsize=10)
ax.set_ylim(0, max(ttr_vals) * 1.15)
for bar, v in zip(bars, ttr_vals):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.001,
            f"{v:.3f}", ha="center", fontsize=9, color=TXT, fontweight="bold")

# (1,0~1) 상위 Vague Phrase 빈도 (가로 막대, 상위 25개)
ax = fig1.add_subplot(gs[1, :2])
dark_ax(ax, "상위 Vague Phrase 빈도 (Active 발굴 포함, 상위 25개)")
top25_phrases = list(phrase_freq.items())[:25]
labels_p = [textwrap.shorten(p, width=50, placeholder="...") for p, _ in top25_phrases]
vals_p   = [v for _, v in top25_phrases]
colors_p = [RED if p in SEED_VAGUE else GOLD for p, _ in top25_phrases]
y_pos = np.arange(len(labels_p))
ax.barh(y_pos, vals_p, color=colors_p, edgecolor=BG, height=0.7)
ax.set_yticks(y_pos)
ax.set_yticklabels(labels_p, fontsize=8.5, color=TXT)
ax.set_xlabel("등장 횟수", color=TXT, fontsize=10)
ax.invert_yaxis()
from matplotlib.patches import Patch
legend_elements = [Patch(facecolor=RED, label="사전 정의 (Seed)"),
                   Patch(facecolor=GOLD, label="Active 발굴")]
ax.legend(handles=legend_elements, facecolor=BG, labelcolor=TXT, fontsize=10)
for i, v in enumerate(vals_p):
    ax.text(v + 5, i, f"{v} ({v/N:.1%})", va="center", fontsize=8, color=TXT)

# (1,2) 캡션 길이 분포 (히스토그램)
ax = fig1.add_subplot(gs[1, 2])
dark_ax(ax, "캡션 길이 분포 (문자 수)")
lengths = [len(r["text"]) for r in records]
ax.hist(lengths, bins=50, color=BLUE, edgecolor=BG, alpha=0.9)
ax.axvline(np.mean(lengths), color=GOLD, linestyle="--", linewidth=1.5, label=f"평균 {np.mean(lengths):.0f}자")
ax.axvline(np.median(lengths), color=GRN, linestyle="--", linewidth=1.5, label=f"중앙값 {np.median(lengths):.0f}자")
ax.set_xlabel("캡션 길이 (문자 수)", color=TXT, fontsize=10)
ax.set_ylabel("빈도", color=TXT, fontsize=10)
ax.legend(facecolor=BG, labelcolor=TXT, fontsize=9)

# (2,0~1) 8-gram 반복 템플릿 빈도
ax = fig1.add_subplot(gs[2, :2])
dark_ax(ax, "가장 많이 반복된 8-gram 템플릿 (상위 15개)")
top8_labels = [textwrap.shorten(p, width=55, placeholder="...") for p, _ in top8[:15]]
top8_vals   = [c for _, c in top8[:15]]
y8 = np.arange(len(top8_labels))
ax.barh(y8, top8_vals, color="#7B1FA2", edgecolor=BG, height=0.7)
ax.set_yticks(y8)
ax.set_yticklabels(top8_labels, fontsize=8.5, color=TXT)
ax.set_xlabel("등장 횟수", color=TXT, fontsize=10)
ax.invert_yaxis()
for i, v in enumerate(top8_vals):
    ax.text(v + 3, i, f"{v} ({v/N:.1%})", va="center", fontsize=8.5, color=TXT)

# (2,2) 첫 문장 도입부 패턴 빈도
ax = fig1.add_subplot(gs[2, 2])
dark_ax(ax, "첫 5단어 도입부 패턴 (상위 12개)")
fw_labels = [textwrap.shorten(p, width=35, placeholder="...") for p, _ in top_first_5w[:12]]
fw_vals   = [c for _, c in top_first_5w[:12]]
y_fw = np.arange(len(fw_labels))
ax.barh(y_fw, fw_vals, color="#00897B", edgecolor=BG, height=0.7)
ax.set_yticks(y_fw)
ax.set_yticklabels(fw_labels, fontsize=8.5, color=TXT)
ax.set_xlabel("등장 횟수", color=TXT, fontsize=10)
ax.invert_yaxis()
for i, v in enumerate(fw_vals):
    ax.text(v + 3, i, f"{v}", va="center", fontsize=9, color=TXT)

fig1.savefig(OUT_DIR / "01_caption_analysis_overview.png",
             dpi=150, bbox_inches="tight", facecolor=BG)
plt.close(fig1)
print("\n💾 Figure 1 저장 완료")


# ── [Figure 2] 카테고리별 상세 비교 ──────────────────────────────
fig2, axes2 = plt.subplots(2, 2, figsize=(20, 14), facecolor=BG)
fig2.suptitle("FakeClue — 카테고리별 Caption 품질 상세 비교",
              color=TXT, fontsize=18, fontweight="bold", y=0.98)
plt.subplots_adjust(hspace=0.4, wspace=0.3, top=0.93, bottom=0.08)

cates_v = [c for c in CATE_ORDER if c in cate_stats]
x = np.arange(len(cates_v))
w = 0.45

# (0,0) 평균 캡션 길이
ax = axes2[0, 0]
dark_ax(ax, "카테고리별 평균 캡션 길이 (문자)")
avg_lens = [cate_stats[c]["avg_len"] for c in cates_v]
bars = ax.bar(cates_v, avg_lens, color=BLUE, edgecolor=BG, width=0.6)
ax.set_xticklabels(cates_v, rotation=30, ha="right", fontsize=10, color=TXT)
ax.set_ylabel("평균 문자 수", color=TXT)
for bar, v in zip(bars, avg_lens):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5,
            f"{v:.0f}", ha="center", fontsize=10, color=TXT, fontweight="bold")

# (0,1) 중복 캡션 비율
ax = axes2[0, 1]
dark_ax(ax, "카테고리별 완전 중복 캡션 비율")
dup_vals = [cate_stats[c]["dup_ratio"] * 100 for c in cates_v]
colors_dup = [RED if v > 5 else GRN for v in dup_vals]
bars = ax.bar(cates_v, dup_vals, color=colors_dup, edgecolor=BG, width=0.6)
ax.set_xticklabels(cates_v, rotation=30, ha="right", fontsize=10, color=TXT)
ax.set_ylabel("중복 비율 (%)", color=TXT)
ax.axhline(5, color=GOLD, linestyle="--", linewidth=1.2, alpha=0.7, label="5% 기준선")
ax.legend(facecolor=BG, labelcolor=TXT, fontsize=9)
for bar, v in zip(bars, dup_vals):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.2,
            f"{v:.1f}%", ha="center", fontsize=10, color=TXT, fontweight="bold")

# (1,0) Vague phrase 포함 비율 (전체)
ax = axes2[1, 0]
dark_ax(ax, "카테고리별 전체 Vague 비율")
vague_vals = [cate_stats[c]["vague_ratio"] * 100 for c in cates_v]
colors_vague = plt.cm.RdYlGn_r(np.array(vague_vals) / 100)
bars = ax.bar(cates_v, vague_vals, color=colors_vague, edgecolor=BG, width=0.6)
ax.set_xticklabels(cates_v, rotation=30, ha="right", fontsize=10, color=TXT)
ax.set_ylabel("Vague 포함 비율 (%)", color=TXT)
ax.set_ylim(0, 115)
for bar, v in zip(bars, vague_vals):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,
            f"{v:.1f}%", ha="center", fontsize=10, color=TXT, fontweight="bold")

# (1,1) Fake vs Real vague 비율 차이
ax = axes2[1, 1]
dark_ax(ax, "Fake vs Real 캡션 Vague 비율 차이")
fake_vv = [cate_stats[c]["fake_vague"] * 100 for c in cates_v]
real_vv = [cate_stats[c]["real_vague"] * 100 for c in cates_v]
diff_vv = [f - r for f, r in zip(fake_vv, real_vv)]
colors_diff = [RED if d > 0 else GRN for d in diff_vv]
bars = ax.bar(cates_v, diff_vv, color=colors_diff, edgecolor=BG, width=0.6)
ax.axhline(0, color=TXT, linewidth=1)
ax.set_xticklabels(cates_v, rotation=30, ha="right", fontsize=10, color=TXT)
ax.set_ylabel("Fake Vague% - Real Vague%", color=TXT)
for bar, v in zip(bars, diff_vv):
    ypos = bar.get_height() + 0.5 if v >= 0 else bar.get_height() - 2
    ax.text(bar.get_x() + bar.get_width()/2, ypos,
            f"{v:+.1f}%", ha="center", fontsize=10, color=TXT, fontweight="bold")

fig2.savefig(OUT_DIR / "02_category_detail.png",
             dpi=150, bbox_inches="tight", facecolor=BG)
plt.close(fig2)
print("💾 Figure 2 저장 완료")


# ── [Figure 3] Word Cloud + Phrase Heatmap ────────────────────────
fig3 = plt.figure(figsize=(22, 10), facecolor=BG)
fig3.suptitle("FakeClue — Caption 어휘 패턴 분석",
              color=TXT, fontsize=18, fontweight="bold", y=1.01)
gs3 = gridspec.GridSpec(1, 2, figure=fig3, wspace=0.1,
                        left=0.01, right=0.99, top=0.92, bottom=0.02)

# (a) WordCloud — 전체 캡션 워드클라우드
ax_wc = fig3.add_subplot(gs3[0])
ax_wc.set_facecolor(BG)
all_text = " ".join(all_lowers)
STOPWORDS = {"the", "a", "an", "is", "are", "it", "its", "this", "that",
             "and", "or", "of", "in", "to", "for", "with", "as", "be",
             "has", "have", "by", "on", "at", "from", "which", "these",
             "also", "further", "more", "such", "than", "not", "no",
             "but", "while", "however", "image", "images", "photo"}
wc = WordCloud(
    width=1100, height=600,
    background_color="#16213e",
    colormap="RdYlGn",
    max_words=180,
    stopwords=STOPWORDS,
    font_path="/Library/Fonts/Arial Unicode.ttf",
    collocations=True,
).generate(all_text)
ax_wc.imshow(wc, interpolation="bilinear")
ax_wc.axis("off")
ax_wc.set_title("전체 Caption 워드클라우드", color=TXT, fontsize=14, fontweight="bold", pad=8)

# (b) Top-20 Phrase × Category Heatmap
ax_hm = fig3.add_subplot(gs3[1])
ax_hm.set_facecolor(CARD)
top20_phrases = list(phrase_freq.items())[:20]
hm_labels = [textwrap.shorten(p, width=45, placeholder="...") for p, _ in top20_phrases]
hm_data = np.zeros((len(top20_phrases), len(cates_v)))
for ci, c in enumerate(cates_v):
    sub_lower = [r["lower"] for r in records if r["cate"] == c]
    n_sub = len(sub_lower)
    for pi, (p, _) in enumerate(top20_phrases):
        cnt = sum(1 for t in sub_lower if p in t)
        hm_data[pi, ci] = cnt / n_sub * 100

im = ax_hm.imshow(hm_data, aspect="auto", cmap="RdYlGn_r", vmin=0, vmax=100)
ax_hm.set_xticks(range(len(cates_v)))
ax_hm.set_xticklabels(cates_v, rotation=30, ha="right", fontsize=10, color=TXT)
ax_hm.set_yticks(range(len(hm_labels)))
ax_hm.set_yticklabels(hm_labels, fontsize=8, color=TXT)
ax_hm.set_title("Phrase × 카테고리 Heatmap (%)", color=TXT, fontsize=14, fontweight="bold", pad=8)
cbar = plt.colorbar(im, ax=ax_hm, fraction=0.03, pad=0.02)
cbar.ax.tick_params(colors=TXT)
cbar.set_label("등장 비율 (%)", color=TXT, fontsize=10)
for pi in range(len(top20_phrases)):
    for ci in range(len(cates_v)):
        v = hm_data[pi, ci]
        ax_hm.text(ci, pi, f"{v:.0f}", ha="center", va="center",
                   fontsize=7.5, color="white" if v > 50 else "black", fontweight="bold")

fig3.savefig(OUT_DIR / "03_wordcloud_heatmap.png",
             dpi=150, bbox_inches="tight", facecolor=BG)
plt.close(fig3)
print("💾 Figure 3 저장 완료")


# ── 9. 분석 의견 텍스트 저장 ─────────────────────────────────────
opinion = f"""
============================================================
FakeClue Caption Quality Analysis — 분석 의견
============================================================

[핵심 수치 요약]
- 총 캡션: {N:,}개
- Vague phrase 포함: {n_vague:,}개 ({n_vague/N:.1%})
- Active 발굴 phrase 수: {len(ALL_VAGUE) - len(SEED_VAGUE)}개 (seed {len(SEED_VAGUE)}개 → 총 {len(ALL_VAGUE)}개)
- 가장 빈출 8-gram: "{top8[0][0]}" ({top8[0][1]}회, {top8[0][1]/N:.1%})
- 가장 많이 반복된 첫 문장: "{top_first_sent[0][0][:70]}..." ({top_first_sent[0][1]}회)

[분석 의견]

1. **템플릿 복붙 수준의 반복성**
   상위 8-gram 구절들이 전체의 {top8[0][1]/N:.0%}~{top8[2][1]/N:.0%} 비율로 반복됩니다.
   "this is a fake image" 류의 첫 문장도 수백 회 동일하게 등장합니다.
   이는 캡션이 실제 이미지를 세밀히 관찰하여 작성된 것이 아니라,
   소수의 템플릿을 재조합한 것에 불과할 가능성을 강하게 시사합니다.

2. **Vague phrase의 전방위적 사용**
   "{list(phrase_freq.keys())[0]}" 등 모호한 결론형 표현이
   전체 캡션의 높은 비율에서 발견됩니다.
   특히 Real(label=1) 캡션에서도 Vague phrase 비율이 높게 나타나는 카테고리가 있어,
   Real/Fake 구분 없이 동일한 템플릿이 무차별적으로 사용되었음을 시사합니다.

3. **카테고리 간 균질성 문제**
   TTR(Type-Token Ratio)가 카테고리 전반에 걸쳐 낮은 편입니다.
   deepfake 카테고리가 얼굴 아티팩트에 특화된 어휘를 다소 사용하는 반면,
   satellite·doc·scene 등은 더욱 획일화된 표현에 의존합니다.
   도메인별 fine-grained reasoning이 부재함을 의미합니다.

4. **신뢰도 평가**
   FakeClue의 GT reasoning은 "실제로 무엇이 이상한지" 설명하는 데 있어
   구체성이 현저히 부족하며, 상당 부분이 자동화 파이프라인 또는
   소수 템플릿의 재조합으로 생성되었을 가능성이 높습니다.
   이는 해당 GT를 supervision signal로 사용하는 모델의 reasoning 능력 평가에
   근본적인 편향을 초래할 수 있습니다.

5. **연구적 시사점**
   - GT 캡션의 표면적 다양성 지표(예: BLEU, ROUGE)만으로는 품질을 평가할 수 없음.
   - FakeVLM 등 모델이 높은 성능을 보이더라도, 그것이 진정한 reasoning인지
     템플릿 암기(memorization)인지 구별이 필요함.
   - Phrase-level vagueness score를 별도 평가 지표로 도입할 필요가 있음.
============================================================
"""
print(opinion)
with open(OUT_DIR / "analysis_opinion.txt", "w", encoding="utf-8") as f:
    f.write(opinion)

print(f"\n✅ 분석 완료! 결과물: {OUT_DIR}")
